config/routes.rb
Rails.application.routes.draw do
  resources :organic_links

   root 'search#google'
   get "/google_search" => 'search#google_search'

end

app/models/organic_link.rb
class OrganicLink < ActiveRecord::Base


	validates :link, :search, :presence => true
	validates_uniqueness_of :link, :scope => :search


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/organic_links_controller.rb
class OrganicLinksController < ApplicationController
  before_action :set_organic_link, only: [:show, :edit, :update, :destroy]

  # GET /organic_links
  # GET /organic_links.json
  def index
    @organic_links = OrganicLink.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /organic_links/1
  # GET /organic_links/1.json
  def show
  end

  # GET /organic_links/new
  def new
    @organic_link = OrganicLink.new
  end

  # GET /organic_links/1/edit
  def edit
  end

  # POST /organic_links
  # POST /organic_links.json
  def create
    @organic_link = OrganicLink.new(organic_link_params)

    respond_to do |format|
      if @organic_link.save
        format.html { redirect_to @organic_link, notice: 'Organic link was successfully created.' }
        format.json { render :show, status: :created, location: @organic_link }
      else
        format.html { render :new }
        format.json { render json: @organic_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organic_links/1
  # PATCH/PUT /organic_links/1.json
  def update
    respond_to do |format|
      if @organic_link.update(organic_link_params)
        format.html { redirect_to @organic_link, notice: 'Organic link was successfully updated.' }
        format.json { render :show, status: :ok, location: @organic_link }
      else
        format.html { render :edit }
        format.json { render json: @organic_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organic_links/1
  # DELETE /organic_links/1.json
  def destroy
    @organic_link.destroy
    respond_to do |format|
      format.html { redirect_to organic_links_url, notice: 'Organic link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organic_link
      @organic_link = OrganicLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organic_link_params
      params.require(:organic_link).permit(:name, :link, :search, :options)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def google 
	end

	def google_search
	
		google_search_api = GoogleCustomeSearch.new(params[:q])
		data = google_search_api.response_data

		if data && data['items'].present?
			@arrays_of_links = data['items'].map{|i| i['link']}
			
			@arrays_of_links.each do |link|
				OrganicLink.create(link: link, search: params[:q])
			end
			
			respond_to do |format|
	      		format.html { redirect_to organic_links_url, notice: 'Organic link successfully created.....' }
	    	end
	    else
	    	respond_to do |format|
	      		format.html { redirect_to root_path, notice: 'No Result Found.....' }
	    	end
	    end
	end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organic_links_helper.rb
module OrganicLinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SvliApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/organic_links/_form.html.erb
<%= form_for @organic_link, :html => { :class => "form-horizontal organic_link" } do |f| %>

  <% if @organic_link.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@organic_link.errors.count, "error") %> prohibited this organic_link from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @organic_link.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :link, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link) %>
  </div>
  <div class="form-group">
    <%= f.label :search, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :search, :class => 'form-control' %>
    </div>
    <%=f.error_span(:search) %>
  </div>
  <div class="form-group">
    <%= f.label :options, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :options, :class => 'form-control' %>
    </div>
    <%=f.error_span(:options) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                organic_links_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/organic_links/edit.html.erb
<%- model_class = OrganicLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organic_links/index.html.erb
<%- model_class = OrganicLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<p id="notice"><%= notice %></p>
<div class='row'>
  <div class='span2'>
  </div>
  <div class='span8'>
    <div class="span4">
      <%= link_to t('.new_search', :default => t("helpers.links.new")), root_path, :class => 'btn btn-primary' %></div>
    <div class="span8">
      <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:search) %></th>
      <th><%= model_class.human_attribute_name(:options) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @organic_links.each do |organic_link| %>
      <tr>
        <td><%= link_to organic_link.id, organic_link_path(organic_link) %></td>
        <td><%= organic_link.name %></td>
        <td><%= organic_link.link %></td>
        <td><%= organic_link.search %></td>
        <td><%= organic_link.options %></td>
        <td><%=l organic_link.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_organic_link_path(organic_link), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      organic_link_path(organic_link),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/organic_links/new.html.erb
<%- model_class = OrganicLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organic_links/show.html.erb
<%- model_class = OrganicLink -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @organic_link.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @organic_link.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:search) %>:</strong></dt>
  <dd><%= @organic_link.search %></dd>
  <dt><strong><%= model_class.human_attribute_name(:options) %>:</strong></dt>
  <dd><%= @organic_link.options %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              organic_links_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organic_link_path(@organic_link), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organic_link_path(@organic_link),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/search/google.html.erb
<p id="notice"><%= notice %></p>
<div class="input-group search_box"  style="width:800px; margin:0 auto;">
  <%= form_tag(google_search_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :q, params[:q], placeholder: "Search......", class: 'form-control' %>
    <span class="input-group-btn">
      <%= submit_tag "Search", class: 'btn btn-default' %>
    </span>
  <% end %>
</div>

app/views/search/google_search.html.erb
<script>
  (function() {
    var cx = '014141997428128086086:fgpofjncaqe';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>